Django07/urls.py
from django.contrib import admin
from django.urls import path, include
from catalog import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='home'),
    path('animals/', views.AnimalListView.as_view(), name='animal-list'),
    # path('kino/<int:id>/',views.info, name='info'),
    path('animals/<slug:pk>/<str:name>', views.AnimalDetailView.as_view(), name='animal-detail'),

]

catalog/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Animal(models.Model):
    name = models.CharField(max_length=100,verbose_name='Имя')
    breed = models.CharField(max_length=100, verbose_name='Порода')

    def __str__(self):
        return self.name

    def get_absolute_url(self): # Получает URL страницы объекта
        return reverse('animal-detail',args=[self.id, self.name])

class Client(models.Model):
    first_name = models.CharField(max_length=50,verbose_name='Имя')
    last_name = models.CharField(max_length=50,verbose_name='Фамилия')

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'


class Veterinarian(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    # specialty = models.CharField(max_length=100, verbose_name='Специализация')
    choise = (('Терапевт', 'Терапевт'), ('Хирург', 'Хирург'), ('Дерматолог', 'Дерматолог'),
              ('Гастроэнтеролог', 'Гастроэнтеролог'), ('Кардиолог', 'Кардиолог'),('Ратолог', 'Ратолог'))
    specialty = models.CharField(max_length=50, choices=choise, verbose_name='Специализация')
    def __str__(self):
        return self.specialty


class Appointment(models.Model):
    date = models.DateField()
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    veterinarian = models.ForeignKey(Veterinarian, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.client}'

    def get_absolute_url(self): # Получает URL страницы объекта
        return reverse('animal-detail',args=[self.id, self.client])

catalog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import *
from catalog.models import Animal


# Create your views here.
def index(req):
    return render(req,'index.html')


from django.views import generic
class AnimalListView(generic.ListView):
    model = Animal
    template_name = 'catalogs/animal_list.html'

class AnimalDetailView(generic.DetailView):
    model = Animal
    template_name = 'catalogs/animal_detail.html'



# from django.http import HttpResponse
# def info(req,id):
#     animal=Animal.objects.get(id=id)
#     return HttpResponse(animal.name)

templates/catalogs/animal_detail.html
{% extends 'index.html' %}

{% block content %}
    <h2>Информация о животных</h2>
    <div>
        <h2>Имя: {{ animal.name }}</h2>
        <h2>Порода: {{ animal.breed }}</h2>
        <h2>Хозяин: {{ animal.appointment_set.first.client }}</h2>
        <h2>Специалист: {{ animal.appointment_set.first.veterinarian.specialty}} </h2>
        <h2>Доктор: {{ animal.appointment_set.first.veterinarian.last_name }}{{ animal.appointment_set.first.veterinarian.first_name}}</h2>

        <h2>Дата: {{ animal.appointment_set.first.date }}</h2>
    </div>
{% endblock content %}

templates/catalogs/animal_list.html
{% extends 'index.html' %}

{% block content %}
    <h2>Список животных</h2>
    <ul>
        {% for animal in animal_list %}

        <li>
            <a href="{{ animal.get_absolute_url }}">{{ animal.name }}</a>
            <p>{{ animal.breed }}</p>
        </li>

        {% endfor %}
    </ul>
{% endblock content %}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ветклиника</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
{% block menu %}
    <div class="menu">
        <a href="{% url 'home' %}">Главная</a>
        <a href="{% url 'animal-list' %}">Животные</a>
        <a href="">Клиенты</a>
        <a href="">Врачи</a>


    </div>
{% endblock menu %}
{% block content %}
    <h2>Поликлинника</h2>

{% endblock content %}
</body>
</html>